### ISSUE TITLE
no logs into nginx error log

### ISSUE THREAD

**Issue by ManuelRighi** [SpiderLabs/ModSecurity-nginx#112]
Hello,
I have Ubuntu 16.04.4 LTS, nginx 1.12.2, modsecurity 3.0.2, modsecurity-nginx v1.0.0.

All blocked transactions are not logs into nginx error log, only in the auditlog (if SecAuditEngine are enabled).

Can you help me to understand because blocked transaction aren't logged into nginx error log file ?

Thanks
Manuel

**Comment by csanders-git** [comment]
I'm actually able to reproduce this using https://hub.docker.com/r/owasp/modsecurity/ v3-ubuntu-nginx tag

**Comment by victorhora** [comment]
Thanks for the report folks.

I've confirmed this behaviour on the current version of ModSecurity-nginx. This is related with the log level in Nginx. I'm checking if this was due any change on the connector or Nginx itself.

For now, by changing the log level from the default of "_error_" to "_warn_" on the [error_log](https://nginx.org/en/docs/ngx_core_module.html#error_log) should show the logs as expected.

**Comment by victorhora** [comment]
Folks, the current investigation on this one suggests that it is not really an issue/bug with libModSecurity or the connector, but rather a behaviour change. 

This issue has been addressed at https://github.com/SpiderLabs/ModSecurity-nginx/pull/116 but there's a decision to be made before merging into master as if it makes sense from technical perspective or if users that wish to see disruptive actions on the error_log should simply change the log level.

**Comment by victorhora** [comment]
As such I'm closing this one. Please follow up on #116. Thanks!

**Comment by csanders-git** [comment]
for the record I needed to go not to warn but to info log level.

**Comment by csanders-git** [comment]
In fact, at info log level only the rule itself that blocked is being reported ... AKA the anomaly scoring rule so i'd say this is still an issue @victorhora
